### PR TITLE
Change event to Mystery 2 Draft

### PR DESCRIPTION
**Pull request by pfirpfel**

### CODE REVIEW

**Comment by pfirpfel** [comment]
@j3mdamas Date ok for you?

**Comment by j3mdamas** [comment]
> @j3mdamas Date ok for you?

Thanks for checking, for me it works 🙏

**Comment by j3mdamas** [comment]
@pfirpfel tagging you, in case you missed my answer above

**Comment by pfirpfel** [comment]
Waiting on the booster box to actually arrive before merging.

**Pull request merged**
